on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

name: macOS build
jobs:
    test-macOS:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }} (${{ matrix.python-version}})

        strategy:
            fail-fast: false
            matrix:
              os: ["macOS-latest"]
              python-version: ["3.10"]

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
      
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ matrix.python-version}}
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install uv
                uv pip install --no-cache-dir Cython
                uv pip install -r requirements.txt
                uv pip install -e .
            env:
                UV_SYSTEM_PYTHON: 1
          
          - name: Test import coralnet_toolbox
            run: |
                python -c "import coralnet_toolbox; print('Successfully imported coralnet_toolbox')"
            env:
                UV_SYSTEM_PYTHON: 1