on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

name: Linux build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.10" }
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install uv
              run: |
                  python -m pip install --upgrade pip
                  pip install uv
            - name: Install GDAL
              run: |
                  uv pip install --no-cache-dir Cython
                  uv pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
              env:
                  UV_SYSTEM_PYTHON: 1
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  uv pip install -r requirements.txt
                  uv pip install -e .
              env:
                  UV_SYSTEM_PYTHON: 1
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/