on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

name: Windows build

permissions:
    contents: read

jobs:
    test:
        uses: ./.github/workflows/test.yml
        with:
            os: windows-latest
